export const SET_TRANSACTION = 'SET_TRANSACTION'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_TRANSACTION_LOAD_STATUS = 'SET_TRANSACTION_LOAD_STATUS'
export const SET_UPDATED_TRANSACTION = 'SET_UPDATED_TRANSACTION'
